utils::globalVariables(c("Column.description",
                         "Empty",
                         "Section",
                         "contains",
                         "domain_code",
                         "no_count",
                         "note",
                         "total_variables",
                         "variable"))
